[platformio]
default_envs = gateway
src_dir = firmware

[common]
platform = teensy
board = teensy41
framework = arduino

[env:gateway]
extends = common
build_src_filter = -<*> +<gateway/>

[env:sniffer_freetext]
extends = common
build_src_filter = -<*> +<sniffer_freetext/>

[env:tach_target_test]
extends = common
build_src_filter = -<*> +<tach_target_test/>

[env:tcm_spoof_test]
extends = common
build_src_filter = -<*> +<tcm_spoof_test/>
